version: "3.7"

services:
  trips-api:
    image: trips-api:v1
    container_name: trips-api
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mongodb
    restart: always
    expose:
      - 5000
    ports:
      - '5000:5000'
    networks:
      - trips_api

  mongodb:
    image: mongo:4.2.21-bionic
    container_name: mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongodb:/data
    networks:
      - trips_api

volumes:
  mongodb:
    driver: local

networks:
  trips_api: